---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: demo
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo
subjects:
  - kind: ServiceAccount
    name: demo
    namespace: default
roleRef:
  kind: ClusterRole
  name: demo
  apiGroup: rbac.authorization.k8s.io
