apiVersion: apps/v1
kind: Deployment
metadata:
  name: flappy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flappy
  template:
    metadata:
      labels:
        app: flappy
    spec:
      containers:
        - name: flappy-container
          image: nginx
          resources:
            requests:
              cpu: 10m # Extremely low CPU request
              memory: 10Mi
            limits:
              cpu: 50m # Very tight CPU limit
              memory: 50Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flappy-service
spec:
  selector:
    app: flappy
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flappy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flappy-app
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0 # No delay for scaling down
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0 # No delay for scaling up
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20 # Very low utilization percentage on which we should scale
